package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseBaseDevices;

/**
 * Generated by Jboot.
 */
@Table(tableName = "base_devices", primaryKey = "device_id")
public class BaseDevices extends BaseBaseDevices<BaseDevices> {
	
}
