package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseDeviceFeatured;

/**
 * Generated by Jboot.
 */
@Table(tableName = "device_featured", primaryKey = "device_id")
public class DeviceFeatured extends BaseDeviceFeatured<DeviceFeatured> {
	
}
