package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseDeviceEvaluate;

/**
 * Generated by Jboot.
 */
@Table(tableName = "device_evaluate", primaryKey = "eva_id")
public class DeviceEvaluate extends BaseDeviceEvaluate<DeviceEvaluate> {
	
}
