package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseDeviceColors;

/**
 * Generated by Jboot.
 */
@Table(tableName = "device_colors", primaryKey = "color_id")
public class DeviceColors extends BaseDeviceColors<DeviceColors> {
	
}
