package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseDevicePics;

/**
 * Generated by Jboot.
 */
@Table(tableName = "device_pics", primaryKey = "pic_id")
public class DevicePics extends BaseDevicePics<DevicePics> {
	
}
