package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseEsysOn;

/**
 * Generated by Jboot.
 */
@Table(tableName = "esys_on", primaryKey = "on_name")
public class EsysOn extends BaseEsysOn<EsysOn> {
	
}
