package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseEsysSn;

/**
 * Generated by Jboot.
 */
@Table(tableName = "esys_sn", primaryKey = "sn_name")
public class EsysSn extends BaseEsysSn<EsysSn> {
	
}
