package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseEsysConf;

/**
 * Generated by Jboot.
 */
@Table(tableName = "esys_conf", primaryKey = "conf_id")
public class EsysConf extends BaseEsysConf<EsysConf> {
	
}
