package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseGroupMembers;

/**
 * Generated by Jboot.
 */
@Table(tableName = "group_members", primaryKey = "user_record_id")
public class GroupMembers extends BaseGroupMembers<GroupMembers> {
	
}
