package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseGroupBase;

/**
 * Generated by Jboot.
 */
@Table(tableName = "group_base", primaryKey = "g_id")
public class GroupBase extends BaseGroupBase<GroupBase> {
	
}
