package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuOtherAlarms;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_other_alarms", primaryKey = "alarm_id")
public class MissuOtherAlarms extends BaseMissuOtherAlarms<MissuOtherAlarms> {
	
}
