package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuUsersBinary;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_users_binary", primaryKey = "resource_id")
public class MissuUsersBinary extends BaseMissuUsersBinary<MissuUsersBinary> {
	
}
