package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuGiftsConsume;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_gifts_consume", primaryKey = "consume_id")
public class MissuGiftsConsume extends BaseMissuGiftsConsume<MissuGiftsConsume> {
	
}
