package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuOprlog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_oprlog", primaryKey = "log_id")
public class MissuOprlog extends BaseMissuOprlog<MissuOprlog> {
	
}
