package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuGiftsToJifendetail;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_gifts_to_jifendetail", primaryKey = "detail_id")
public class MissuGiftsToJifendetail extends BaseMissuGiftsToJifendetail<MissuGiftsToJifendetail> {
	
}
