package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuFriendreq;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_friendreq", primaryKey = "be_user_uid,user_uid")
public class MissuFriendreq extends BaseMissuFriendreq<MissuFriendreq> {
	
}
