package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuRoster;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_roster", primaryKey = "friend_user_uid,user_uid")
public class MissuRoster extends BaseMissuRoster<MissuRoster> {
	
}
