package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuOfflineHistory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_offline_history", primaryKey = "history_id")
public class MissuOfflineHistory extends BaseMissuOfflineHistory<MissuOfflineHistory> {
	
}
