package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuUserMsgsCollect;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_user_msgs_collect", primaryKey = "collect_id")
public class MissuUserMsgsCollect extends BaseMissuUserMsgsCollect<MissuUserMsgsCollect> {
	
}
