package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuGifts;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_gifts", primaryKey = "gift_ident")
public class MissuGifts extends BaseMissuGifts<MissuGifts> {
	
}
