package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuGiftsMine;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_gifts_mine", primaryKey = "my_gift_rec_id")
public class MissuGiftsMine extends BaseMissuGiftsMine<MissuGiftsMine> {
	
}
