package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuGiftsToJifen;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_gifts_to_jifen", primaryKey = "rec_id")
public class MissuGiftsToJifen extends BaseMissuGiftsToJifen<MissuGiftsToJifen> {
	
}
