package com.amico.service.im.entity.model;

import com.amico.service.im.entity.model.base.BaseMissuUsers;

import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_users", primaryKey = "user_uid")
public class MissuUsers extends BaseMissuUsers<MissuUsers> {
	
	
}
