package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseMissuBigFiles;

/**
 * Generated by Jboot.
 */
@Table(tableName = "missu_big_files", primaryKey = "resource_id")
public class MissuBigFiles extends BaseMissuBigFiles<MissuBigFiles> {
	
}
