package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BasePaypalPaymentInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "paypal_payment_info", primaryKey = "id")
public class PaypalPaymentInfo extends BasePaypalPaymentInfo<PaypalPaymentInfo> {
	
}
