package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseSalesSoDetail;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sales_so_detail", primaryKey = "so_detail_id")
public class SalesSoDetail extends BaseSalesSoDetail<SalesSoDetail> {
	
}
