package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseSalesSoConsigneeInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sales_so_consignee_info", primaryKey = "order_id")
public class SalesSoConsigneeInfo extends BaseSalesSoConsigneeInfo<SalesSoConsigneeInfo> {
	
}
