package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseSalesCountryTransfer;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sales_country_transfer", primaryKey = "transfer_id")
public class SalesCountryTransfer extends BaseSalesCountryTransfer<SalesCountryTransfer> {
	
}
