package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseSalesCountry;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sales_country", primaryKey = "country_id")
public class SalesCountry extends BaseSalesCountry<SalesCountry> {
	
}
