package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseSalesTrsferForCountry;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sales_trsfer_for_country", primaryKey = "trsfer_for_country_id")
public class SalesTrsferForCountry extends BaseSalesTrsferForCountry<SalesTrsferForCountry> {
	
}
