package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseSalesSo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sales_so", primaryKey = "order_id")
public class SalesSo extends BaseSalesSo<SalesSo> {
	
}
