package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseTokenUserToken;

/**
 * Generated by Jboot.
 */
@Table(tableName = "token_user_token", primaryKey = "user_uid")
public class TokenUserToken extends BaseTokenUserToken<TokenUserToken> {
	
}
