package com.amico.service.im.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.im.entity.model.base.BaseTokenRechangeHistory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "token_rechange_history", primaryKey = "record_id")
public class TokenRechangeHistory extends BaseTokenRechangeHistory<TokenRechangeHistory> {
	
}
