package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAmicoNews;

/**
 * Generated by Jboot.
 */
@Table(tableName = "amico_news", primaryKey = "id")
public class AmicoNews extends BaseAmicoNews<AmicoNews> {
	
}
