package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAmicoNewsCategory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "amico_news_category", primaryKey = "id")
public class AmicoNewsCategory extends BaseAmicoNewsCategory<AmicoNewsCategory> {
	
}
