package com.amico.service.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.entity.model.base.BaseAuthToken;

/**
 * Generated by Jboot.
 */
@Table(tableName = "auth_token", primaryKey = "id")
public class AuthToken extends BaseAuthToken<AuthToken> {
	
}
