package com.amico.service.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.entity.model.base.BaseAuthApp;

/**
 * Generated by Jboot.
 */
@Table(tableName = "auth_app", primaryKey = "id")
public class AuthApp extends BaseAuthApp<AuthApp> {
	
}
