package com.amico.service.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.entity.model.base.BaseAuthRedirectConfig;

/**
 * Generated by Jboot.
 */
@Table(tableName = "auth_redirect_config", primaryKey = "id")
public class AuthRedirectConfig extends BaseAuthRedirectConfig<AuthRedirectConfig> {
	
}
