package com.amico.service.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.entity.model.base.BaseAuthLog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "auth_log", primaryKey = "id")
public class AuthLog extends BaseAuthLog<AuthLog> {
	
}
