package com.amico.service.entity.model;

import io.jboot.db.annotation.Table;
import com.amico.service.entity.model.base.BaseAuthUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "auth_user", primaryKey = "id")
public class AuthUser extends BaseAuthUser<AuthUser> {
	
}
