package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseDevices<M extends BaseBaseDevices<M>> extends JbootModel<M> implements IBean {

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}
	
	public java.lang.String getDeviceId() {
		return getStr("device_id");
	}

	public void setDeviceName(java.lang.String deviceName) {
		set("device_name", deviceName);
	}
	
	public java.lang.String getDeviceName() {
		return getStr("device_name");
	}

	public void setDeviceShortName(java.lang.String deviceShortName) {
		set("device_short_name", deviceShortName);
	}
	
	public java.lang.String getDeviceShortName() {
		return getStr("device_short_name");
	}

	public void setForSex(java.lang.Integer forSex) {
		set("for_sex", forSex);
	}
	
	public java.lang.Integer getForSex() {
		return getInt("for_sex");
	}

	public void setReferencePrice(java.math.BigDecimal referencePrice) {
		set("reference_price", referencePrice);
	}
	
	public java.math.BigDecimal getReferencePrice() {
		return get("reference_price");
	}

	public void setSalePrice(java.math.BigDecimal salePrice) {
		set("sale_price", salePrice);
	}
	
	public java.math.BigDecimal getSalePrice() {
		return get("sale_price");
	}

	public void setSaleCurrencyType(java.lang.Integer saleCurrencyType) {
		set("sale_currency_type", saleCurrencyType);
	}
	
	public java.lang.Integer getSaleCurrencyType() {
		return getInt("sale_currency_type");
	}

	public void setDeviceDesc(java.lang.String deviceDesc) {
		set("device_desc", deviceDesc);
	}
	
	public java.lang.String getDeviceDesc() {
		return getStr("device_desc");
	}

	public void setDeviceBasicInfo(java.lang.String deviceBasicInfo) {
		set("device_basic_info", deviceBasicInfo);
	}
	
	public java.lang.String getDeviceBasicInfo() {
		return getStr("device_basic_info");
	}

	public void setDeviceSaleInfo(java.lang.String deviceSaleInfo) {
		set("device_sale_info", deviceSaleInfo);
	}
	
	public java.lang.String getDeviceSaleInfo() {
		return getStr("device_sale_info");
	}

	public void setDeviceDetailUrl(java.lang.String deviceDetailUrl) {
		set("device_detail_url", deviceDetailUrl);
	}
	
	public java.lang.String getDeviceDetailUrl() {
		return getStr("device_detail_url");
	}

	public void setDeviceModel(java.lang.Integer deviceModel) {
		set("device_model", deviceModel);
	}
	
	public java.lang.Integer getDeviceModel() {
		return getInt("device_model");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

}
