package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSalesCountryTransfer<M extends BaseSalesCountryTransfer<M>> extends JbootModel<M> implements IBean {

	public void setTransferId(java.lang.Integer transferId) {
		set("transfer_id", transferId);
	}
	
	public java.lang.Integer getTransferId() {
		return getInt("transfer_id");
	}

	public void setTransferName(java.lang.String transferName) {
		set("transfer_name", transferName);
	}
	
	public java.lang.String getTransferName() {
		return getStr("transfer_name");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

}
