package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceColors<M extends BaseDeviceColors<M>> extends JbootModel<M> implements IBean {

	public void setColorId(java.lang.String colorId) {
		set("color_id", colorId);
	}
	
	public java.lang.String getColorId() {
		return getStr("color_id");
	}

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}
	
	public java.lang.String getDeviceId() {
		return getStr("device_id");
	}

	public void setColorDesc(java.lang.String colorDesc) {
		set("color_desc", colorDesc);
	}
	
	public java.lang.String getColorDesc() {
		return getStr("color_desc");
	}

	public void setColorName(java.lang.String colorName) {
		set("color_name", colorName);
	}
	
	public java.lang.String getColorName() {
		return getStr("color_name");
	}

}
