package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuUserMsgsCollect<M extends BaseMissuUserMsgsCollect<M>> extends JbootModel<M> implements IBean {

	public void setCollectId(java.lang.Integer collectId) {
		set("collect_id", collectId);
	}
	
	public java.lang.Integer getCollectId() {
		return getInt("collect_id");
	}

	public void setSrcUid(java.lang.Integer srcUid) {
		set("src_uid", srcUid);
	}
	
	public java.lang.Integer getSrcUid() {
		return getInt("src_uid");
	}

	public void setDestUid(java.lang.Integer destUid) {
		set("dest_uid", destUid);
	}
	
	public java.lang.Integer getDestUid() {
		return getInt("dest_uid");
	}

	public void setChatType(java.lang.Integer chatType) {
		set("chat_type", chatType);
	}
	
	public java.lang.Integer getChatType() {
		return getInt("chat_type");
	}

	public void setMsgType(java.lang.Integer msgType) {
		set("msg_type", msgType);
	}
	
	public java.lang.Integer getMsgType() {
		return getInt("msg_type");
	}

	public void setMsgContent(java.lang.String msgContent) {
		set("msg_content", msgContent);
	}
	
	public java.lang.String getMsgContent() {
		return getStr("msg_content");
	}

	public void setMsgTime(java.util.Date msgTime) {
		set("msg_time", msgTime);
	}
	
	public java.util.Date getMsgTime() {
		return get("msg_time");
	}

	public void setOnlineCount(java.lang.Integer onlineCount) {
		set("online_count", onlineCount);
	}
	
	public java.lang.Integer getOnlineCount() {
		return getInt("online_count");
	}

}
