package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEsysOn<M extends BaseEsysOn<M>> extends JbootModel<M> implements IBean {

	public void setOnName(java.lang.String onName) {
		set("on_name", onName);
	}
	
	public java.lang.String getOnName() {
		return getStr("on_name");
	}

	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}
	
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

	public void setFieldName(java.lang.String fieldName) {
		set("field_name", fieldName);
	}
	
	public java.lang.String getFieldName() {
		return getStr("field_name");
	}

	public void setHeadIdent(java.lang.String headIdent) {
		set("head_ident", headIdent);
	}
	
	public java.lang.String getHeadIdent() {
		return getStr("head_ident");
	}

	public void setInterval1(java.lang.String interval1) {
		set("interval1", interval1);
	}
	
	public java.lang.String getInterval1() {
		return getStr("interval1");
	}

	public void setDatePattern(java.lang.String datePattern) {
		set("date_pattern", datePattern);
	}
	
	public java.lang.String getDatePattern() {
		return getStr("date_pattern");
	}

	public void setInterval2(java.lang.String interval2) {
		set("interval2", interval2);
	}
	
	public java.lang.String getInterval2() {
		return getStr("interval2");
	}

	public void setFlowNumDatePattern(java.lang.String flowNumDatePattern) {
		set("flow_num_date_pattern", flowNumDatePattern);
	}
	
	public java.lang.String getFlowNumDatePattern() {
		return getStr("flow_num_date_pattern");
	}

	public void setFlowNumLen(java.lang.Integer flowNumLen) {
		set("flow_num_len", flowNumLen);
	}
	
	public java.lang.Integer getFlowNumLen() {
		return getInt("flow_num_len");
	}

	public void setBz(java.lang.String bz) {
		set("bz", bz);
	}
	
	public java.lang.String getBz() {
		return getStr("bz");
	}

	public void setGenTime(java.util.Date genTime) {
		set("gen_time", genTime);
	}
	
	public java.util.Date getGenTime() {
		return get("gen_time");
	}

}
