package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDevicePics<M extends BaseDevicePics<M>> extends JbootModel<M> implements IBean {

	public void setPicId(java.lang.Integer picId) {
		set("pic_id", picId);
	}
	
	public java.lang.Integer getPicId() {
		return getInt("pic_id");
	}

	public void setColorId(java.lang.String colorId) {
		set("color_id", colorId);
	}
	
	public java.lang.String getColorId() {
		return getStr("color_id");
	}

	public void setPicDesc(java.lang.String picDesc) {
		set("pic_desc", picDesc);
	}
	
	public java.lang.String getPicDesc() {
		return getStr("pic_desc");
	}

	public void setPicPath(java.lang.String picPath) {
		set("pic_path", picPath);
	}
	
	public java.lang.String getPicPath() {
		return getStr("pic_path");
	}

}
