package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuFriendreq<M extends BaseMissuFriendreq<M>> extends JbootModel<M> implements IBean {

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setBeUserUid(java.lang.Integer beUserUid) {
		set("be_user_uid", beUserUid);
	}
	
	public java.lang.Integer getBeUserUid() {
		return getInt("be_user_uid");
	}

	public void setBeDesc(java.lang.String beDesc) {
		set("be_desc", beDesc);
	}
	
	public java.lang.String getBeDesc() {
		return getStr("be_desc");
	}

	public void setBeTime(java.util.Date beTime) {
		set("be_time", beTime);
	}
	
	public java.util.Date getBeTime() {
		return get("be_time");
	}

	public void setBtIp(java.lang.String btIp) {
		set("bt_ip", btIp);
	}
	
	public java.lang.String getBtIp() {
		return getStr("bt_ip");
	}

	public void setBeTimestamp(java.lang.String beTimestamp) {
		set("be_timestamp", beTimestamp);
	}
	
	public java.lang.String getBeTimestamp() {
		return getStr("be_timestamp");
	}

}
