package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaypalPaymentInfo<M extends BasePaypalPaymentInfo<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setPaymentKey(java.lang.String paymentKey) {
		set("payment_key", paymentKey);
	}
	
	public java.lang.String getPaymentKey() {
		return getStr("payment_key");
	}

	public void setPaymentDate(java.lang.String paymentDate) {
		set("payment_date", paymentDate);
	}
	
	public java.lang.String getPaymentDate() {
		return getStr("payment_date");
	}

	public void setPaymentStatus(java.lang.String paymentStatus) {
		set("payment_status", paymentStatus);
	}
	
	public java.lang.String getPaymentStatus() {
		return getStr("payment_status");
	}

	public void setPayerStatus(java.lang.String payerStatus) {
		set("payer_status", payerStatus);
	}
	
	public java.lang.String getPayerStatus() {
		return getStr("payer_status");
	}

	public void setOrderSign(java.lang.String orderSign) {
		set("order_sign", orderSign);
	}
	
	public java.lang.String getOrderSign() {
		return getStr("order_sign");
	}

	public void setInfoContent(java.lang.String infoContent) {
		set("info_content", infoContent);
	}
	
	public java.lang.String getInfoContent() {
		return getStr("info_content");
	}

}
