package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuGiftsConsume<M extends BaseMissuGiftsConsume<M>> extends JbootModel<M> implements IBean {

	public void setConsumeId(java.lang.String consumeId) {
		set("consume_id", consumeId);
	}
	
	public java.lang.String getConsumeId() {
		return getStr("consume_id");
	}

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setMisUserUid(java.lang.Integer misUserUid) {
		set("mis_user_uid", misUserUid);
	}
	
	public java.lang.Integer getMisUserUid() {
		return getInt("mis_user_uid");
	}

	public void setGiftIdent(java.lang.String giftIdent) {
		set("gift_ident", giftIdent);
	}
	
	public java.lang.String getGiftIdent() {
		return getStr("gift_ident");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}

	public void setConsumeTime(java.util.Date consumeTime) {
		set("consume_time", consumeTime);
	}
	
	public java.util.Date getConsumeTime() {
		return get("consume_time");
	}

	public void setConsumeTime2(java.lang.String consumeTime2) {
		set("consume_time2", consumeTime2);
	}
	
	public java.lang.String getConsumeTime2() {
		return getStr("consume_time2");
	}

}
