package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTokenUserToken<M extends BaseTokenUserToken<M>> extends JbootModel<M> implements IBean {

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setCurrentTokenCount(java.lang.Integer currentTokenCount) {
		set("current_token_count", currentTokenCount);
	}
	
	public java.lang.Integer getCurrentTokenCount() {
		return getInt("current_token_count");
	}

}
