package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceEvaluate<M extends BaseDeviceEvaluate<M>> extends JbootModel<M> implements IBean {

	public void setEvaId(java.lang.Integer evaId) {
		set("eva_id", evaId);
	}
	
	public java.lang.Integer getEvaId() {
		return getInt("eva_id");
	}

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}
	
	public java.lang.String getDeviceId() {
		return getStr("device_id");
	}

	public void setForUserUid(java.lang.Integer forUserUid) {
		set("for_user_uid", forUserUid);
	}
	
	public java.lang.Integer getForUserUid() {
		return getInt("for_user_uid");
	}

	public void setEvaContent(java.lang.String evaContent) {
		set("eva_content", evaContent);
	}
	
	public java.lang.String getEvaContent() {
		return getStr("eva_content");
	}

	public void setEvaTime(java.util.Date evaTime) {
		set("eva_time", evaTime);
	}
	
	public java.util.Date getEvaTime() {
		return get("eva_time");
	}

	public void setSoDetailId(java.lang.String soDetailId) {
		set("so_detail_id", soDetailId);
	}
	
	public java.lang.String getSoDetailId() {
		return getStr("so_detail_id");
	}

	public void setEvaScore(java.lang.Integer evaScore) {
		set("eva_score", evaScore);
	}
	
	public java.lang.Integer getEvaScore() {
		return getInt("eva_score");
	}

}
