package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuUsers<M extends BaseMissuUsers<M>> extends JbootModel<M> implements IBean {

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setUserMail(java.lang.String userMail) {
		set("user_mail", userMail);
	}
	
	public java.lang.String getUserMail() {
		return getStr("user_mail");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setUserPsw(java.lang.String userPsw) {
		set("user_psw", userPsw);
	}
	
	public java.lang.String getUserPsw() {
		return getStr("user_psw");
	}

	public void setUserSex(java.lang.Integer userSex) {
		set("user_sex", userSex);
	}
	
	public java.lang.Integer getUserSex() {
		return getInt("user_sex");
	}

	public void setRegisterIp(java.lang.String registerIp) {
		set("register_ip", registerIp);
	}
	
	public java.lang.String getRegisterIp() {
		return getStr("register_ip");
	}

	public void setRegisterTime(java.util.Date registerTime) {
		set("register_time", registerTime);
	}
	
	public java.util.Date getRegisterTime() {
		return get("register_time");
	}

	public void setLatestLoginTime(java.util.Date latestLoginTime) {
		set("latest_login_time", latestLoginTime);
	}
	
	public java.util.Date getLatestLoginTime() {
		return get("latest_login_time");
	}

	public void setLatestLoginTime2(java.lang.String latestLoginTime2) {
		set("latest_login_time2", latestLoginTime2);
	}
	
	public java.lang.String getLatestLoginTime2() {
		return getStr("latest_login_time2");
	}

	public void setLatestLoginIp(java.lang.String latestLoginIp) {
		set("latest_login_ip", latestLoginIp);
	}
	
	public java.lang.String getLatestLoginIp() {
		return getStr("latest_login_ip");
	}

	public void setUserStatus(java.lang.Integer userStatus) {
		set("user_status", userStatus);
	}
	
	public java.lang.Integer getUserStatus() {
		return getInt("user_status");
	}

	public void setIsOnline(java.lang.Integer isOnline) {
		set("is_online", isOnline);
	}
	
	public java.lang.Integer getIsOnline() {
		return getInt("is_online");
	}

	public void setVerificationCode(java.lang.String verificationCode) {
		set("verification_code", verificationCode);
	}
	
	public java.lang.String getVerificationCode() {
		return getStr("verification_code");
	}

	public void setVerificationTime(java.lang.String verificationTime) {
		set("verification_time", verificationTime);
	}
	
	public java.lang.String getVerificationTime() {
		return getStr("verification_time");
	}

	public void setUserAvatarFileName(java.lang.String userAvatarFileName) {
		set("user_avatar_file_name", userAvatarFileName);
	}
	
	public java.lang.String getUserAvatarFileName() {
		return getStr("user_avatar_file_name");
	}

	public void setWhatSUp(java.lang.String whatSUp) {
		set("what_s_up", whatSUp);
	}
	
	public java.lang.String getWhatSUp() {
		return getStr("what_s_up");
	}

	public void setMaxFriend(java.lang.Integer maxFriend) {
		set("max_friend", maxFriend);
	}
	
	public java.lang.Integer getMaxFriend() {
		return getInt("max_friend");
	}

	public void setUserDesc(java.lang.String userDesc) {
		set("user_desc", userDesc);
	}
	
	public java.lang.String getUserDesc() {
		return getStr("user_desc");
	}

	public void setUserType(java.lang.Integer userType) {
		set("user_type", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("user_type");
	}

	public void setUserRegieon(java.lang.String userRegieon) {
		set("user_regieon", userRegieon);
	}
	
	public java.lang.String getUserRegieon() {
		return getStr("user_regieon");
	}

	public void setIosDeviceToken(java.lang.String iosDeviceToken) {
		set("ios_device_token", iosDeviceToken);
	}
	
	public java.lang.String getIosDeviceToken() {
		return getStr("ios_device_token");
	}
	
	public void setUserPhone(java.lang.String userPhone) {
		set("user_phone", userPhone);
	}
	
	public java.lang.String getUserPhone() {
		return getStr("user_phone");
	}
	
	public void setAndroidDeviceToken(java.lang.String androidDeviceToken) {
		set("android_device_token", androidDeviceToken);
	}
	
	public java.lang.String getAndroidDeviceToken() {
		return getStr("android_device_token");
	}
	
	
}
