package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupBase<M extends BaseGroupBase<M>> extends JbootModel<M> implements IBean {

	public void setGId(java.lang.String gId) {
		set("g_id", gId);
	}
	
	public java.lang.String getGId() {
		return getStr("g_id");
	}

	public void setGStatus(java.lang.Integer gStatus) {
		set("g_status", gStatus);
	}
	
	public java.lang.Integer getGStatus() {
		return getInt("g_status");
	}

	public void setGName(java.lang.String gName) {
		set("g_name", gName);
	}
	
	public java.lang.String getGName() {
		return getStr("g_name");
	}

	public void setGOwnerUserUid(java.lang.Integer gOwnerUserUid) {
		set("g_owner_user_uid", gOwnerUserUid);
	}
	
	public java.lang.Integer getGOwnerUserUid() {
		return getInt("g_owner_user_uid");
	}

	public void setGNotice(java.lang.String gNotice) {
		set("g_notice", gNotice);
	}
	
	public java.lang.String getGNotice() {
		return getStr("g_notice");
	}

	public void setMaxMemberCount(java.lang.Integer maxMemberCount) {
		set("max_member_count", maxMemberCount);
	}
	
	public java.lang.Integer getMaxMemberCount() {
		return getInt("max_member_count");
	}

	public void setGMemberCount(java.lang.Integer gMemberCount) {
		set("g_member_count", gMemberCount);
	}
	
	public java.lang.Integer getGMemberCount() {
		return getInt("g_member_count");
	}

	public void setCreateUserUid(java.lang.Integer createUserUid) {
		set("create_user_uid", createUserUid);
	}
	
	public java.lang.Integer getCreateUserUid() {
		return getInt("create_user_uid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setForbidUserUid(java.lang.Integer forbidUserUid) {
		set("forbid_user_uid", forbidUserUid);
	}
	
	public java.lang.Integer getForbidUserUid() {
		return getInt("forbid_user_uid");
	}

	public void setForbidTime(java.util.Date forbidTime) {
		set("forbid_time", forbidTime);
	}
	
	public java.util.Date getForbidTime() {
		return get("forbid_time");
	}

	public void setFirbidCause(java.lang.String firbidCause) {
		set("firbid_cause", firbidCause);
	}
	
	public java.lang.String getFirbidCause() {
		return getStr("firbid_cause");
	}

	public void setGNoticeUpdatetime(java.util.Date gNoticeUpdatetime) {
		set("g_notice_updatetime", gNoticeUpdatetime);
	}
	
	public java.util.Date getGNoticeUpdatetime() {
		return get("g_notice_updatetime");
	}

	public void setGNoticeUpdateuid(java.lang.Integer gNoticeUpdateuid) {
		set("g_notice_updateuid", gNoticeUpdateuid);
	}
	
	public java.lang.Integer getGNoticeUpdateuid() {
		return getInt("g_notice_updateuid");
	}

	public void setDelUserUid(java.lang.Integer delUserUid) {
		set("del_user_uid", delUserUid);
	}
	
	public java.lang.Integer getDelUserUid() {
		return getInt("del_user_uid");
	}

	public void setDelTime(java.util.Date delTime) {
		set("del_time", delTime);
	}
	
	public java.util.Date getDelTime() {
		return get("del_time");
	}

	public void setAvatarIncludeCnt(java.lang.Integer avatarIncludeCnt) {
		set("avatar_include_cnt", avatarIncludeCnt);
	}
	
	public java.lang.Integer getAvatarIncludeCnt() {
		return getInt("avatar_include_cnt");
	}

}
