package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSalesSoConsigneeInfo<M extends BaseSalesSoConsigneeInfo<M>> extends JbootModel<M> implements IBean {

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setConsigneeSurname(java.lang.String consigneeSurname) {
		set("consignee_surname", consigneeSurname);
	}
	
	public java.lang.String getConsigneeSurname() {
		return getStr("consignee_surname");
	}

	public void setConsigneeName(java.lang.String consigneeName) {
		set("consignee_name", consigneeName);
	}
	
	public java.lang.String getConsigneeName() {
		return getStr("consignee_name");
	}

	public void setCountryOfConsignee(java.lang.Integer countryOfConsignee) {
		set("country_of_consignee", countryOfConsignee);
	}
	
	public java.lang.Integer getCountryOfConsignee() {
		return getInt("country_of_consignee");
	}

	public void setCityOfConsignee(java.lang.String cityOfConsignee) {
		set("city_of_consignee", cityOfConsignee);
	}
	
	public java.lang.String getCityOfConsignee() {
		return getStr("city_of_consignee");
	}

	public void setAddrOfConsignee(java.lang.String addrOfConsignee) {
		set("addr_of_consignee", addrOfConsignee);
	}
	
	public java.lang.String getAddrOfConsignee() {
		return getStr("addr_of_consignee");
	}

	public void setCodeOfConsignee(java.lang.String codeOfConsignee) {
		set("code_of_consignee", codeOfConsignee);
	}
	
	public java.lang.String getCodeOfConsignee() {
		return getStr("code_of_consignee");
	}

	public void setMailOfConsignee(java.lang.String mailOfConsignee) {
		set("mail_of_consignee", mailOfConsignee);
	}
	
	public java.lang.String getMailOfConsignee() {
		return getStr("mail_of_consignee");
	}

	public void setPhoneOfConsignee(java.lang.String phoneOfConsignee) {
		set("phone_of_consignee", phoneOfConsignee);
	}
	
	public java.lang.String getPhoneOfConsignee() {
		return getStr("phone_of_consignee");
	}

	public void setAppender(java.lang.String appender) {
		set("appender", appender);
	}
	
	public java.lang.String getAppender() {
		return getStr("appender");
	}

}
