package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuOtherAlarms<M extends BaseMissuOtherAlarms<M>> extends JbootModel<M> implements IBean {

	public void setAlarmId(java.lang.Integer alarmId) {
		set("alarm_id", alarmId);
	}
	
	public java.lang.Integer getAlarmId() {
		return getInt("alarm_id");
	}

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setAlarmType(java.lang.Integer alarmType) {
		set("alarm_type", alarmType);
	}
	
	public java.lang.Integer getAlarmType() {
		return getInt("alarm_type");
	}

	public void setAlarmTitle(java.lang.String alarmTitle) {
		set("alarm_title", alarmTitle);
	}
	
	public java.lang.String getAlarmTitle() {
		return getStr("alarm_title");
	}

	public void setAlarmMsgContent(java.lang.String alarmMsgContent) {
		set("alarm_msg_content", alarmMsgContent);
	}
	
	public java.lang.String getAlarmMsgContent() {
		return getStr("alarm_msg_content");
	}

	public void setAlarmTime(java.lang.String alarmTime) {
		set("alarm_time", alarmTime);
	}
	
	public java.lang.String getAlarmTime() {
		return getStr("alarm_time");
	}

	public void setOtherDesc(java.lang.String otherDesc) {
		set("other_desc", otherDesc);
	}
	
	public java.lang.String getOtherDesc() {
		return getStr("other_desc");
	}

}
