package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuOprlog<M extends BaseMissuOprlog<M>> extends JbootModel<M> implements IBean {

	public void setLogId(java.lang.Integer logId) {
		set("log_id", logId);
	}
	
	public java.lang.Integer getLogId() {
		return getInt("log_id");
	}

	public void setUserUid(java.lang.String userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.String getUserUid() {
		return getStr("user_uid");
	}

	public void setOprType(java.lang.Integer oprType) {
		set("opr_type", oprType);
	}
	
	public java.lang.Integer getOprType() {
		return getInt("opr_type");
	}

	public void setOprDesc(java.lang.String oprDesc) {
		set("opr_desc", oprDesc);
	}
	
	public java.lang.String getOprDesc() {
		return getStr("opr_desc");
	}

	public void setOprContent(java.lang.String oprContent) {
		set("opr_content", oprContent);
	}
	
	public java.lang.String getOprContent() {
		return getStr("opr_content");
	}

	public void setOprTime(java.util.Date oprTime) {
		set("opr_time", oprTime);
	}
	
	public java.util.Date getOprTime() {
		return get("opr_time");
	}

	public void setOprBz(java.lang.String oprBz) {
		set("opr_bz", oprBz);
	}
	
	public java.lang.String getOprBz() {
		return getStr("opr_bz");
	}

}
