package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeviceFeatured<M extends BaseDeviceFeatured<M>> extends JbootModel<M> implements IBean {

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}
	
	public java.lang.String getDeviceId() {
		return getStr("device_id");
	}

	public void setPicPath(java.lang.String picPath) {
		set("pic_path", picPath);
	}
	
	public java.lang.String getPicPath() {
		return getStr("pic_path");
	}

	public void setPicDesc(java.lang.String picDesc) {
		set("pic_desc", picDesc);
	}
	
	public java.lang.String getPicDesc() {
		return getStr("pic_desc");
	}

	public void setValid(java.lang.Integer valid) {
		set("valid", valid);
	}
	
	public java.lang.Integer getValid() {
		return getInt("valid");
	}

}
