package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuGiftsToJifendetail<M extends BaseMissuGiftsToJifendetail<M>> extends JbootModel<M> implements IBean {

	public void setDetailId(java.lang.Integer detailId) {
		set("detail_id", detailId);
	}
	
	public java.lang.Integer getDetailId() {
		return getInt("detail_id");
	}

	public void setRecId(java.lang.String recId) {
		set("rec_id", recId);
	}
	
	public java.lang.String getRecId() {
		return getStr("rec_id");
	}

	public void setFromUserUid(java.lang.Integer fromUserUid) {
		set("from_user_uid", fromUserUid);
	}
	
	public java.lang.Integer getFromUserUid() {
		return getInt("from_user_uid");
	}

	public void setGiftIdent(java.lang.String giftIdent) {
		set("gift_ident", giftIdent);
	}
	
	public java.lang.String getGiftIdent() {
		return getStr("gift_ident");
	}

	public void setJifenAmount(java.lang.Integer jifenAmount) {
		set("jifen_amount", jifenAmount);
	}
	
	public java.lang.Integer getJifenAmount() {
		return getInt("jifen_amount");
	}

	public void setGetTime(java.util.Date getTime) {
		set("get_time", getTime);
	}
	
	public java.util.Date getGetTime() {
		return get("get_time");
	}

	public void setGetTime2(java.lang.String getTime2) {
		set("get_time2", getTime2);
	}
	
	public java.lang.String getGetTime2() {
		return getStr("get_time2");
	}

}
