package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuBigFiles<M extends BaseMissuBigFiles<M>> extends JbootModel<M> implements IBean {

	public void setResourceId(java.lang.Integer resourceId) {
		set("resource_id", resourceId);
	}
	
	public java.lang.Integer getResourceId() {
		return getInt("resource_id");
	}

	public void setResType(java.lang.Integer resType) {
		set("res_type", resType);
	}
	
	public java.lang.Integer getResType() {
		return getInt("res_type");
	}

	public void setResFileName(java.lang.String resFileName) {
		set("res_file_name", resFileName);
	}
	
	public java.lang.String getResFileName() {
		return getStr("res_file_name");
	}

	public void setResHumanSize(java.lang.String resHumanSize) {
		set("res_human_size", resHumanSize);
	}
	
	public java.lang.String getResHumanSize() {
		return getStr("res_human_size");
	}

	public void setResSize(java.math.BigDecimal resSize) {
		set("res_size", resSize);
	}
	
	public java.math.BigDecimal getResSize() {
		return get("res_size");
	}

	public void setResMd5(java.lang.String resMd5) {
		set("res_md5", resMd5);
	}
	
	public java.lang.String getResMd5() {
		return getStr("res_md5");
	}

	public void setDownloadCount(java.lang.Integer downloadCount) {
		set("download_count", downloadCount);
	}
	
	public java.lang.Integer getDownloadCount() {
		return getInt("download_count");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserUid(java.lang.Integer createUserUid) {
		set("create_user_uid", createUserUid);
	}
	
	public java.lang.Integer getCreateUserUid() {
		return getInt("create_user_uid");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
	}
	
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	public void setFileStatus(java.lang.Integer fileStatus) {
		set("file_status", fileStatus);
	}
	
	public java.lang.Integer getFileStatus() {
		return getInt("file_status");
	}

}
