package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEsysConf<M extends BaseEsysConf<M>> extends JbootModel<M> implements IBean {

	public void setConfId(java.lang.String confId) {
		set("conf_id", confId);
	}
	
	public java.lang.String getConfId() {
		return getStr("conf_id");
	}

	public void setConfVal(java.lang.String confVal) {
		set("conf_val", confVal);
	}
	
	public java.lang.String getConfVal() {
		return getStr("conf_val");
	}

	public void setDefaultVal(java.lang.String defaultVal) {
		set("default_val", defaultVal);
	}
	
	public java.lang.String getDefaultVal() {
		return getStr("default_val");
	}

	public void setOther1(java.lang.String other1) {
		set("other1", other1);
	}
	
	public java.lang.String getOther1() {
		return getStr("other1");
	}

	public void setBz(java.lang.String bz) {
		set("bz", bz);
	}
	
	public java.lang.String getBz() {
		return getStr("bz");
	}

	public void setOther2(java.lang.String other2) {
		set("other2", other2);
	}
	
	public java.lang.String getOther2() {
		return getStr("other2");
	}

	public void setOther3(java.lang.String other3) {
		set("other3", other3);
	}
	
	public java.lang.String getOther3() {
		return getStr("other3");
	}

	public void setGenTime(java.util.Date genTime) {
		set("gen_time", genTime);
	}
	
	public java.util.Date getGenTime() {
		return get("gen_time");
	}

}
