package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuGiftsToJifen<M extends BaseMissuGiftsToJifen<M>> extends JbootModel<M> implements IBean {

	public void setRecId(java.lang.String recId) {
		set("rec_id", recId);
	}
	
	public java.lang.String getRecId() {
		return getStr("rec_id");
	}

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setJifenAmount(java.lang.Integer jifenAmount) {
		set("jifen_amount", jifenAmount);
	}
	
	public java.lang.Integer getJifenAmount() {
		return getInt("jifen_amount");
	}

	public void setChargeTime(java.util.Date chargeTime) {
		set("charge_time", chargeTime);
	}
	
	public java.util.Date getChargeTime() {
		return get("charge_time");
	}

	public void setChargeTime2(java.lang.String chargeTime2) {
		set("charge_time2", chargeTime2);
	}
	
	public java.lang.String getChargeTime2() {
		return getStr("charge_time2");
	}

}
