package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSalesCountry<M extends BaseSalesCountry<M>> extends JbootModel<M> implements IBean {

	public void setCountryId(java.lang.Integer countryId) {
		set("country_id", countryId);
	}
	
	public java.lang.Integer getCountryId() {
		return getInt("country_id");
	}

	public void setCountryName(java.lang.String countryName) {
		set("country_name", countryName);
	}
	
	public java.lang.String getCountryName() {
		return getStr("country_name");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("is_valid", isValid);
	}
	
	public java.lang.Integer getIsValid() {
		return getInt("is_valid");
	}

}
