package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuOfflineHistory<M extends BaseMissuOfflineHistory<M>> extends JbootModel<M> implements IBean {

	public void setHistoryId(java.lang.Integer historyId) {
		set("history_id", historyId);
	}
	
	public java.lang.Integer getHistoryId() {
		return getInt("history_id");
	}

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setFriendUserUid(java.lang.Integer friendUserUid) {
		set("friend_user_uid", friendUserUid);
	}
	
	public java.lang.Integer getFriendUserUid() {
		return getInt("friend_user_uid");
	}

	public void setHistoryType(java.lang.Integer historyType) {
		set("history_type", historyType);
	}
	
	public java.lang.Integer getHistoryType() {
		return getInt("history_type");
	}

	public void setHistoryContent(java.lang.String historyContent) {
		set("history_content", historyContent);
	}
	
	public java.lang.String getHistoryContent() {
		return getStr("history_content");
	}

	public void setHistoryContent2(java.lang.String historyContent2) {
		set("history_content2", historyContent2);
	}
	
	public java.lang.String getHistoryContent2() {
		return getStr("history_content2");
	}

	public void setHistoryTime2(java.lang.String historyTime2) {
		set("history_time2", historyTime2);
	}
	
	public java.lang.String getHistoryTime2() {
		return getStr("history_time2");
	}

	public void setHistoryTime(java.util.Date historyTime) {
		set("history_time", historyTime);
	}
	
	public java.util.Date getHistoryTime() {
		return get("history_time");
	}

	public void setChatType(java.lang.Integer chatType) {
		set("chat_type", chatType);
	}
	
	public java.lang.Integer getChatType() {
		return getInt("chat_type");
	}

	public void setGroupId(java.lang.String groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.String getGroupId() {
		return getStr("group_id");
	}

}
