package com.amico.service.im.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMissuRoster<M extends BaseMissuRoster<M>> extends JbootModel<M> implements IBean {

	public void setUserUid(java.lang.Integer userUid) {
		set("user_uid", userUid);
	}
	
	public java.lang.Integer getUserUid() {
		return getInt("user_uid");
	}

	public void setFriendUserUid(java.lang.Integer friendUserUid) {
		set("friend_user_uid", friendUserUid);
	}
	
	public java.lang.Integer getFriendUserUid() {
		return getInt("friend_user_uid");
	}

	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}
	
	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
