package com.amico.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthUser<M extends BaseAuthUser<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setUserRealName(java.lang.String userRealName) {
		set("user_real_name", userRealName);
	}
	
	public java.lang.String getUserRealName() {
		return getStr("user_real_name");
	}

	public void setUserAddress(java.lang.String userAddress) {
		set("user_address", userAddress);
	}
	
	public java.lang.String getUserAddress() {
		return getStr("user_address");
	}

	public void setUserGender(java.lang.String userGender) {
		set("user_gender", userGender);
	}
	
	public java.lang.String getUserGender() {
		return getStr("user_gender");
	}

	public void setUserAge(java.lang.String userAge) {
		set("user_age", userAge);
	}
	
	public java.lang.String getUserAge() {
		return getStr("user_age");
	}

	public void setUserMail(java.lang.String userMail) {
		set("user_mail", userMail);
	}
	
	public java.lang.String getUserMail() {
		return getStr("user_mail");
	}

	public void setUserMoblie(java.lang.String userMoblie) {
		set("user_moblie", userMoblie);
	}
	
	public java.lang.String getUserMoblie() {
		return getStr("user_moblie");
	}

	public void setUserAccount(java.lang.String userAccount) {
		set("user_account", userAccount);
	}
	
	public java.lang.String getUserAccount() {
		return getStr("user_account");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("user_pwd", userPwd);
	}
	
	public java.lang.String getUserPwd() {
		return getStr("user_pwd");
	}

	public void setUserPhoto(java.lang.String userPhoto) {
		set("user_photo", userPhoto);
	}
	
	public java.lang.String getUserPhoto() {
		return getStr("user_photo");
	}

}
