package com.amico.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthRedirectConfig<M extends BaseAuthRedirectConfig<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	public void setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.String getDelFlag() {
		return getStr("del_flag");
	}

	public void setThirdPartyHttp(java.lang.String thirdPartyHttp) {
		set("third_party_http", thirdPartyHttp);
	}
	
	public java.lang.String getThirdPartyHttp() {
		return getStr("third_party_http");
	}

	public void setThirdPartyParam(java.lang.String thirdPartyParam) {
		set("third_party_param", thirdPartyParam);
	}
	
	public java.lang.String getThirdPartyParam() {
		return getStr("third_party_param");
	}

	public void setThirdPartyName(java.lang.String thirdPartyName) {
		set("third_party_name", thirdPartyName);
	}
	
	public java.lang.String getThirdPartyName() {
		return getStr("third_party_name");
	}

	public void setCertIds(java.lang.String certIds) {
		set("cert_ids", certIds);
	}
	
	public java.lang.String getCertIds() {
		return getStr("cert_ids");
	}

	public void setIsOff(java.lang.String isOff) {
		set("is_off", isOff);
	}
	
	public java.lang.String getIsOff() {
		return getStr("is_off");
	}

	public void setIsAutoCommit(java.lang.String isAutoCommit) {
		set("is_auto_commit", isAutoCommit);
	}
	
	public java.lang.String getIsAutoCommit() {
		return getStr("is_auto_commit");
	}

	public void setAppId(java.lang.String appId) {
		set("app_id", appId);
	}
	
	public java.lang.String getAppId() {
		return getStr("app_id");
	}

	public void setRedirectType(java.lang.String redirectType) {
		set("redirect_type", redirectType);
	}
	
	public java.lang.String getRedirectType() {
		return getStr("redirect_type");
	}

}
