// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseProto.proto

package com.amico.service.im.net.req.protobuf;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseMessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ResponseMessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string errorNo = 1;</code>
     */
    boolean hasErrorNo();
    /**
     * <code>required string errorNo = 1;</code>
     */
    java.lang.String getErrorNo();
    /**
     * <code>required string errorNo = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorNoBytes();

    /**
     * <code>required string errorInfo = 2;</code>
     */
    boolean hasErrorInfo();
    /**
     * <code>required string errorInfo = 2;</code>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>required string errorInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();

    /**
     * <code>required string className = 3;</code>
     */
    boolean hasClassName();
    /**
     * <code>required string className = 3;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 3;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>required bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code protobuf.ResponseMessageProto}
   */
  public  static final class ResponseMessageProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.ResponseMessageProto)
      ResponseMessageProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMessageProto.newBuilder() to construct.
    private ResponseMessageProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessageProto() {
      errorNo_ = "";
      errorInfo_ = "";
      className_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessageProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              errorNo_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorInfo_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              className_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amico.service.im.net.req.protobuf.ResponseProto.internal_static_protobuf_ResponseMessageProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amico.service.im.net.req.protobuf.ResponseProto.internal_static_protobuf_ResponseMessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.class, com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.Builder.class);
    }

    private int bitField0_;
    public static final int ERRORNO_FIELD_NUMBER = 1;
    private volatile java.lang.Object errorNo_;
    /**
     * <code>required string errorNo = 1;</code>
     */
    public boolean hasErrorNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string errorNo = 1;</code>
     */
    public java.lang.String getErrorNo() {
      java.lang.Object ref = errorNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string errorNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorNoBytes() {
      java.lang.Object ref = errorNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORINFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorInfo_;
    /**
     * <code>required string errorInfo = 2;</code>
     */
    public boolean hasErrorInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string errorInfo = 2;</code>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string errorInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object className_;
    /**
     * <code>required string className = 3;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string className = 3;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string className = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrorNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClassName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, className_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, className_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto)) {
        return super.equals(obj);
      }
      com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto other = (com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto) obj;

      boolean result = true;
      result = result && (hasErrorNo() == other.hasErrorNo());
      if (hasErrorNo()) {
        result = result && getErrorNo()
            .equals(other.getErrorNo());
      }
      result = result && (hasErrorInfo() == other.hasErrorInfo());
      if (hasErrorInfo()) {
        result = result && getErrorInfo()
            .equals(other.getErrorInfo());
      }
      result = result && (hasClassName() == other.hasClassName());
      if (hasClassName()) {
        result = result && getClassName()
            .equals(other.getClassName());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrorNo()) {
        hash = (37 * hash) + ERRORNO_FIELD_NUMBER;
        hash = (53 * hash) + getErrorNo().hashCode();
      }
      if (hasErrorInfo()) {
        hash = (37 * hash) + ERRORINFO_FIELD_NUMBER;
        hash = (53 * hash) + getErrorInfo().hashCode();
      }
      if (hasClassName()) {
        hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
        hash = (53 * hash) + getClassName().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ResponseMessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ResponseMessageProto)
        com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amico.service.im.net.req.protobuf.ResponseProto.internal_static_protobuf_ResponseMessageProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amico.service.im.net.req.protobuf.ResponseProto.internal_static_protobuf_ResponseMessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.class, com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.Builder.class);
      }

      // Construct using com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorNo_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        errorInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amico.service.im.net.req.protobuf.ResponseProto.internal_static_protobuf_ResponseMessageProto_descriptor;
      }

      public com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto getDefaultInstanceForType() {
        return com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.getDefaultInstance();
      }

      public com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto build() {
        com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto buildPartial() {
        com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto result = new com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorNo_ = errorNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorInfo_ = errorInfo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.className_ = className_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto) {
          return mergeFrom((com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto other) {
        if (other == com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto.getDefaultInstance()) return this;
        if (other.hasErrorNo()) {
          bitField0_ |= 0x00000001;
          errorNo_ = other.errorNo_;
          onChanged();
        }
        if (other.hasErrorInfo()) {
          bitField0_ |= 0x00000002;
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        if (other.hasClassName()) {
          bitField0_ |= 0x00000004;
          className_ = other.className_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorNo()) {
          return false;
        }
        if (!hasErrorInfo()) {
          return false;
        }
        if (!hasClassName()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object errorNo_ = "";
      /**
       * <code>required string errorNo = 1;</code>
       */
      public boolean hasErrorNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string errorNo = 1;</code>
       */
      public java.lang.String getErrorNo() {
        java.lang.Object ref = errorNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string errorNo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorNoBytes() {
        java.lang.Object ref = errorNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string errorNo = 1;</code>
       */
      public Builder setErrorNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string errorNo = 1;</code>
       */
      public Builder clearErrorNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorNo_ = getDefaultInstance().getErrorNo();
        onChanged();
        return this;
      }
      /**
       * <code>required string errorNo = 1;</code>
       */
      public Builder setErrorNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        errorNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorInfo_ = "";
      /**
       * <code>required string errorInfo = 2;</code>
       */
      public boolean hasErrorInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string errorInfo = 2;</code>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string errorInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string errorInfo = 2;</code>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string errorInfo = 2;</code>
       */
      public Builder clearErrorInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>required string errorInfo = 2;</code>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorInfo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <code>required string className = 3;</code>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string className = 3;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            className_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string className = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string className = 3;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 3;</code>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 3;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        className_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.ResponseMessageProto)
    }

    // @@protoc_insertion_point(class_scope:protobuf.ResponseMessageProto)
    private static final com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto();
    }

    public static com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResponseMessageProto>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessageProto>() {
      public ResponseMessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseMessageProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMessageProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessageProto> getParserForType() {
      return PARSER;
    }

    public com.amico.service.im.net.req.protobuf.ResponseProto.ResponseMessageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ResponseMessageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_ResponseMessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ResponseProto.proto\022\010protobuf\"[\n\024Respo" +
      "nseMessageProto\022\017\n\007errorNo\030\001 \002(\t\022\021\n\terro" +
      "rInfo\030\002 \002(\t\022\021\n\tclassName\030\003 \002(\t\022\014\n\004data\030\004" +
      " \002(\014B6\n%com.amico.service.im.net.req.pro" +
      "tobufB\rResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_ResponseMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_ResponseMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_ResponseMessageProto_descriptor,
        new java.lang.String[] { "ErrorNo", "ErrorInfo", "ClassName", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
